sm6150: Add missing prototype to fix `[-Werror,-Wstrict-prototypes]` errors
../../../../../../kernel/samsung/sm6150/drivers/afc/pm6150-afc.c:415:11: error: a function declaration without a prototype is deprecated
 in all versions of C [-Werror,-Wstrict-prototypes]

../../../../../../kernel/samsung/sm6150/drivers/soc/qcom/memshare/msm_memshare.c:52:8: error: type specifier missing, defaults to 'int'
[-Werror,-Wimplicit-int]
extern sec_reserved_mem(void);

../../../../../../kernel/samsung/sm6150/drivers/gpu/drm/msm/samsung/ss_dsi_panel_debug.c:249:8: error: type specifier missing, d
efaults to 'int' [-Werror,-Wimplicit-int]

 ../../../../../../kernel/samsung/sm6150/drivers/staging/qca-wifi-host-cmn/hif/src/ce/ce_service.c:2805:34: error: a function declaration
 without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()

../../../../../../kernel/samsung/sm6150/drivers/staging/qca-wifi-host-cmn/target_if/core/src/target_if_main.c:81:40: error: a function d
eclaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()

../../../../../../kernel/samsung/sm6150/drivers/staging/qca-wifi-host-cmn/wlan_cfg/wlan_cfg.c:292:49: error: a function declaration with
out a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct wlan_cfg_dp_soc_ctxt *wlan_cfg_soc_attach()

../../../../../../kernel/samsung/sm6150/mm/zsmalloc.c:2483:29: error: a function declaration without a prototype is deprecated in all ve
rsions of C [-Werror,-Wstrict-prototypes]

Change-Id: I99cc4ee32ab45c877a46d9a02d1621a917b3ffd9